## Configuracion de Instancia
server:
    port: 8080

## Configuracion del cliente de Eureka
eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
    instance:
        preferIpAddress: true
        hostname: ms-libro-products

## Configuracion de Spring 
spring:
    application:
        name: ms-libro-products
    datasource:
        url: jdbc:postgresql://localhost:5432/actividadDos
        username: postgres
        password: Alexander1991
        initialization-mode: always
        data: classpath:/data.sql
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true

