## Configuracion de Instancia
server:
    port: 8082

## Configuracion del cliente de Eureka
eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
    instance:
        preferIpAddress: true
        #valida que este arriba caso contrario lo elimina
        lease-renewal-interval-in-seconds: 30
        lease-expiration-duration-in-seconds: 90
    hostname: ms-alquiler-orders

## Configuracion de Spring
spring:
    application:
        name: ms-alquiler-orders
    datasource:
        url: jdbc:mysql://localhost:3306/actividadDos?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
        username: root
        password: Alexander1991
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create

## Configuracion secundaria (custom)
getLibro:
    url: http://ms-libro-products/libros/%s
    urlAlquiler: http://ms-libro-products/alquilar/%s

